### ISSUE TITLE
Can you do only downsampling without transcription?

### ISSUE THREAD

**Issue by WorkManOne** [gabcodedev/Tacotron2AutoTrim#1]
I just want to convert my 41100hz wavs to 22050.

**Comment by gabcodedev** [comment]
Downsampling code is included in load.py file, you can just use pydub for that.  This script is used for auto trim and auto transcribe files (it also converts the wav files to 22050 hz as I said before).

**Comment by gabcodedev** [comment]
`import pydub
from pydub import AudioSegment
import os

directory_path = 'wavs'

for file in os.listdir(directory_path):
    sound_file = AudioSegment.from_file(directory_path+f'/{file}')
    sound_file = sound_file.set_frame_rate(22050)  # sets the file to 22050 hz
    sound_file = sound_file.set_channels(1)  # converts the file to mono
    sound_file.export(directory_path+f'/{file}', format='wav')`

This code should work, create a new file called for example "down.py" and paste this code into it. Then paste the down.py file in the same directory as your "wavs" folder and run `python down.py`

This will downsample all the files in the wavs folder to 22050 hz. Hope it helps.
