### ISSUE TITLE
UnicodeEncodeerror: 'charmap'

### ISSUE THREAD

**Issue by krigeta** [gabcodedev/Tacotron2AutoTrim#14]
Hello, I am trying to trim clean Japanese vocals and got this error:

```
audio-chunks\1.wav : ������ .
Traceback (most recent call last):
File "load.py", line 136, in <module>
File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11-16: character maps to <undefined>
[1496] Failed to execute script load
```
whats the fix?

**Comment by gabcodedev** [comment]
Hello, I didn't test the script with japanese audios, I tought it would work out of the box, guess I was wrong. Can you send me the input audio file so I can test it and fix it, please?

**Comment by krigeta** [comment]
yeah, here it is
[vocals.zip](https://github.com/gabcodedev/Tacotron2AutoTrim/files/6638114/vocals.zip)

**Comment by gabcodedev** [comment]
Fixed, just clone or download the repo and do `python load.py`
I don't have time to compile an executable now, that's why you should use python for now. I'll upload the exe soon.

**Comment by gabcodedev** [comment]
wait don't do that, sorry I just realized in the list.txt the characters are not printed well.

**Comment by gabcodedev** [comment]
let me fix it again xD

**Comment by gabcodedev** [comment]
okay now fixed 100%

**Comment by gabcodedev** [comment]
I don't know if it will work tough, because Japanese encoding is in utf-16, normal encoding most of the time is utf-8. Never tested Tacotron 2 training with utf-16 so maybe it gives you problems, just try it and please tell me if it worked , good luck!

**Comment by krigeta** [comment]
So I have installed the `imageio-ffmpeg` but in console it is still saying that 

```
"C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\imageio\plugins\ffmpeg.py", line 37, in download
    raise RuntimeError(
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'
```

**Comment by gabcodedev** [comment]
You have to install the requirements in the "requirements.txt" file so do `pip install -r requirements.txt`

This is because the most recent versions of imageio don't contain ffmpeg directly, you have to use an older version.

**Comment by krigeta** [comment]
okay let me try that

**Comment by krigeta** [comment]
so good news and bad news its partially working but for stopped and when it is executing the split part the error was for every wav but finally its partially working.

if you are good with bash scripting may you please help me with a little bit of change I need to make in a bash script?

**Comment by gabcodedev** [comment]
It's partially working because the quality of the audio is not very good. If you try another audio with better quality it will probably work much better.

And I don't know bash scripting but shouldn't be too dificult. What do you want me to help you with?

**Comment by gabcodedev** [comment]
Sorry I don't understand How are you going to use both repos together?

The other repo just gives you timestamps.

**Comment by krigeta** [comment]
It is returning me the output audio file which has all of the dialouges according to the timestamp occuurence.
