### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by Elmhart** [gabcodedev/Tacotron2AutoTrim#2]
I followed the instructions, but got these errors when I tried to use python load.py:
![code](https://user-images.githubusercontent.com/80600910/114901749-b7fa5600-9dda-11eb-90bf-4d97d46b315a.JPG)

I am very new to python and would appreciate your help!

**Comment by gabcodedev** [comment]
Make sure to install ffmpeg and add it to Path variable in windows.

**Comment by gabcodedev** [comment]
I just released the .exe. You can run it directly and it will work.

**Comment by Elmhart** [comment]
Thank you!!
