### ISSUE TITLE
Tacotron2AutoTrim.exe

### ISSUE THREAD

**Issue by Nesggy** [gabcodedev/Tacotron2AutoTrim#5]
In your github it says run Tacotron2AutoTrim.exe, except I don't have this file. What do I do?

**Comment by erikp** [comment]
I'm confused/blocked by this as well :/

**Comment by erikp** [comment]
@Nesggy  I found links to the .exe's in a previous version. Maybe they got lost in the latest merge? My git-fu is weak.
https://github.com/gabcodedev/Tacotron2AutoTrim/releases/tag/1.3

**Comment by Nesggy** [comment]
Thanks. I've already found it a few days ago
