### ISSUE TITLE
Shows RuntimeWarning: Couldn't find ffmpeg or avconv

### ISSUE THREAD

**Issue by blacknyx** [gabcodedev/Tacotron2AutoTrim#7]
This shows up when i run the script, and then the output folder is empty (like it doesn't work at all)

This is what shows up
"C:\Users\Username\AppData\Local\Temp\_MEI121402\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work "

**Comment by gabcodedev** [comment]
Hello, I just updated the exe, can you download it again from the 1.5 release and let me know if it works please?
