### ISSUE TITLE
No input or output

### ISSUE THREAD

**Issue by Mike0004895** [gabcodedev/Tacotron2AutoTrim#9]
This program is not working.
![sda](https://user-images.githubusercontent.com/63241177/120944171-10761180-c701-11eb-91db-d64bd05939e9.PNG)

**Comment by MinecrasfsftMan** [comment]
OMG I HAD THIS BEFORE!

**Comment by Mike0004895** [comment]
WAIT WHAT?

**Comment by MrMeany** [comment]
Man, this person is super lazy!

**Comment by Mike0004895** [comment]
Yeah! He makes scams, dude!

**Comment by MinecrasfsftMan** [comment]
Yeah, I had a virus dectection.

**Comment by Mike0004895** [comment]
Yeah, it's not working. It is a virus. I will report this.

**Comment by MrMeany** [comment]
Can the creator at least try?

**Comment by MinecrasfsftMan** [comment]
"Nope" -gabcodedev

**Comment by MinecrasfsftMan** [comment]
![2b2d8790-3c6a-11e7-8ee3-761f02c18070_image_hires_204107](https://user-images.githubusercontent.com/71991306/120944463-a78f9900-c702-11eb-8daf-4bb82ffa240a.png)
That's what scammers look like in real life

**Comment by MrMeany** [comment]
LOL!

**Comment by Mike0004895** [comment]
FUNNY!

**Comment by Mike0004895** [comment]
Pretty sure that sums up how people are nowadays, not telling us THE DIRECTIONS! NOT EVERYONE KNOWS PYTHON!

**Comment by Mike0004895** [comment]
I used python, and I know a little bit of it.

**Comment by Mike0004895** [comment]
DUDE WHAT IS A SILENCE THRESH???

**Comment by MrMeany** [comment]
YEAH!

**Comment by MinecrasfsftMan** [comment]
The creator is probably like: ...

**Comment by Mike0004895** [comment]
THEY THINK THAT EVERYONE KNOWS WHAT A SILENCE THRESH IS!

**Comment by Mike0004895** [comment]
To sum it up: people here are too lazy to fix the simplest things.
